baseURL = 'https://PaintCartel.github.io/knowledgebase/'
languageCode = 'en-us'
title = 'PaintCartel'
theme = 'm10c'

[params]
  author = "Brian Chambers"
  description = "Knowledge-Base in progress."
  menu_item_seperator = "***"
[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about hugo'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110
[[menu.main]]
  identifier = 'Tags'
  name = 'Tags mentioned in posts'
  pre = "<i class='fa fa-heart'></i>"
  url = '/tags/'
  weight = -110
  [menu.main.params]
    class = 'highlight-menu-item'