baseURL = 'https://PaintCartel.github.io/knowledgebase/'
languageCode = 'en-us'
title = 'PaintCartel'
theme = 'm10c'

[params]
  author = "Brian Chambers"
  description = "Knowledge-Base in progress."

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"